# Generated by Django 5.0.6 on 2024-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='azzii', max_length=100, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Статья - Введи текст')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
